---
title: "Base R Graphics"
output:
  html_document:
    df_print: paged
---

# A Simple example


```{r create data frame,cache=TRUE}
dose <- seq(20,60,10)
drugA <- c(16,20,27,40,60)
drugB <- c(15,18,25,31,40)
```


```{r simple plot}
opar <- par(no.readonly=TRUE)
par(lty=2, pch=17)
plot(dose, drugA, type="b")
par(opar)
```

Add some color.


```{r more color}
library(RColorBrewer)
n <-7
mycolors <- brewer.pal(n, "Set1")
barplot(rep(1,n), col=mycolors)
```


Here the simple plot again

```{r color to simple plot, cache=FALSE}
# from https://r-charts.com/base-r/background-color/#background-color-plot
opar <- par(no.readonly=TRUE)
par(bg="#717171", fg="blue")

plot(dose, drugA)

rect(par("usr")[1], par("usr")[3],
     par("usr")[2], par("usr")[4],
     col = "#A1A1A1") # Color

par(new = plot)

plot(dose, drugA, type="b",
     lty=2, pch=17,
     col = 'blue',
     col.axis = "blue",
     col.lab = "blue",
     col.main = "blue",
     main = "Test blue graph background",
     xlab = "Dose in Units/kg body weight",
     ylab ="Drug A"
     )
abline(a = 10, b = 0.3, lty=2, pch=17, col= "blue")

par(opar)
```

